- name: Totebag Bordir Bunga
  desc: Tas Tote Bag dengan bordir bunga di kedua sisi, Bahan Kain SAB, Bordir Manual ( Juki )
  price: 40k
  image: https://images.tokopedia.net/img/cache/700/VqbcmM/2021/3/21/11cb5ceb-b6be-4008-9bec-7df520330dcf.jpg
  url: https://www.tokopedia.com/as-syariahbordir/totebag-bordir-bunga-hitam?whid=0

- name: masker 3d bordir
  desc: Masker 3D bordir dengan 3 lapisan., bordir manual tasik. Dengan bahan kain 100% katun 3 lapisan
  price: 28k
  image: https://images.tokopedia.net/img/cache/700/VqbcmM/2021/2/9/5cfe6de1-8b22-476a-9253-3c9fd8bf62c3.jpg
  url: https://www.tokopedia.com/as-syariahbordir/masker-3d-bordir-3lapisan-toska-earloop?whid=0

- name: masker Bordir Setaman
  desc: masker Bordir dengan 3 lapisan, Bordir Juki, Tali Karet, HeadLoop & Earloop.
  price: 16k
  image: https://images.tokopedia.net/img/cache/700/VqbcmM/2021/1/27/9360de7a-4b16-46af-bcf3-9a028d75a4d2.jpg
  url: https://www.tokopedia.com/as-syariahbordir/masker-bordir-bunga-setaman-navi-ikat

- name: Masker Bordir Rosse
  desc: Masker Bordir Motif, cantik dan nyaman dipakai. Bordir manual (JUKI) dengan bahan kain 100% katun 3 lapisan
  price: 16k
  image: https://images.tokopedia.net/img/cache/700/VqbcmM/2021/1/20/99ba098a-7867-4ef1-87d0-e7c0791a1076.jpg
  url: https://www.tokopedia.com/as-syariahbordir/masker-bordir-motif-rosse-navi-tali-ikat

- name: Masker Bordir Tulip
  desc: Masker Bordir Motif, cantik dan nyaman dipakai. Bordir manual (JUKI) dengan bahan kain 100% katun 3 lapisan
  price: 16k
  image: https://images.tokopedia.net/img/cache/700/VqbcmM/2021/1/17/df3572ad-0920-4512-abdf-58251501d23e.jpg
  url: https://www.tokopedia.com/as-syariahbordir/masker-bordir-bunga-ungu-tali-ikat
